
INSERT INTO orders (ORDER_ID, EMAIL_ADDRESS, RETURN_ORDER_ID ) VALUES ('RK-478', 'john@example.com', null);
INSERT INTO orders (ORDER_ID, EMAIL_ADDRESS, RETURN_ORDER_ID) VALUES ('RK-642', 'will@example.com', null);
INSERT INTO orders (ORDER_ID, EMAIL_ADDRESS, RETURN_ORDER_ID) VALUES ('RK-238', 'carly@example.com', null);
INSERT INTO orders (ORDER_ID, EMAIL_ADDRESS, RETURN_ORDER_ID) VALUES ('RK-912', 'karen@example.com', null);
INSERT INTO orders (ORDER_ID, EMAIL_ADDRESS, RETURN_ORDER_ID) VALUES ('RK-239', 'steve@example.com', null);
INSERT INTO orders (ORDER_ID, EMAIL_ADDRESS, RETURN_ORDER_ID) VALUES ('RK-149', 'dalton@example.com', null);

INSERT INTO items (ITEM_ID, ORDER_ID, SKU, QUANTITY, PRICE, ITEM_NAME, QC_STATUS, RETURN_ORDER_ID) VALUES (123, 'RK-478','MENS-156', 2, 50, 'Small Black T-Shirt', null, null);
INSERT INTO items (ITEM_ID, ORDER_ID, SKU, QUANTITY, PRICE, ITEM_NAME, QC_STATUS, RETURN_ORDER_ID) VALUES (124, 'RK-478','NIKE-7', 1, 110.75, 'Nike Air Jordans - Size 7', null, null);
INSERT INTO items (ITEM_ID, ORDER_ID, SKU, QUANTITY, PRICE, ITEM_NAME, QC_STATUS, RETURN_ORDER_ID) VALUES (125, 'RK-642','SOC-1', 2, 50, 'Soccer Ball', null, null);
INSERT INTO items (ITEM_ID, ORDER_ID, SKU, QUANTITY, PRICE, ITEM_NAME, QC_STATUS, RETURN_ORDER_ID) VALUES (126, 'RK-238','MU-5091', 3, 25.99, 'Lip Gloss', null, null);
INSERT INTO items (ITEM_ID, ORDER_ID, SKU, QUANTITY, PRICE, ITEM_NAME, QC_STATUS, RETURN_ORDER_ID) VALUES (127, 'RK-238','NIKE-56', 1, 15.25, 'Nike Medium Red Leggings', null, null);
INSERT INTO items (ITEM_ID, ORDER_ID, SKU, QUANTITY, PRICE, ITEM_NAME, QC_STATUS, RETURN_ORDER_ID) VALUES (128, 'RK-238','MU-4129', 2, 75.5, 'Eye Shadow', null, null);
INSERT INTO items (ITEM_ID, ORDER_ID, SKU, QUANTITY, PRICE, ITEM_NAME, QC_STATUS, RETURN_ORDER_ID) VALUES (129, 'RK-912','PAR-14', 1, 149.99, 'Chanel - CHANCE EAU FRAÎCHE Eau de Toilette', null, null);
INSERT INTO items (ITEM_ID, ORDER_ID, SKU, QUANTITY, PRICE, ITEM_NAME, QC_STATUS, RETURN_ORDER_ID) VALUES (130, 'RK-239','MENS-156', 1, 50, 'Small Black T-Shirt', null, null);
INSERT INTO items (ITEM_ID, ORDER_ID, SKU, QUANTITY, PRICE, ITEM_NAME, QC_STATUS, RETURN_ORDER_ID) VALUES (131, 'RK-149','SOC-1', 1, 25.99, 'Soccer Ball', null, null);
INSERT INTO items (ITEM_ID, ORDER_ID, SKU, QUANTITY, PRICE, ITEM_NAME, QC_STATUS, RETURN_ORDER_ID) VALUES (132, 'RK-149','NIKE-143', 2, 249.99, 'Nike Mercurial Superfly 8 Elite FG Firm Ground Soccer Cleat', null, null);


